Микросервис отзывов
joshkhdev/psy-assist-platform-feedback pull request #1
Opened 2024-08-16 22:19 UTC by miitrei

2024-08-18 16:38 UTC, joshkhdev requested changes

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/FeedbackMessagesService.cs
> +            return;
Этот сценарий похож на Exception
Не должно приходить Publish, если нет текста или имени пользователя, а если приходит - нужно кинуть Exception

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/FeedbackService.cs
> +    private const string EmptyTelegramMessage = "Telegram cannot be empty";
Думаю это называется Telegram id, в сообщениях думаю его так и нужно называть

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/TelegramBotService.cs
> +    private const string HelloMessage = "������ ����! ����� �������� �����, �������, ����������, � ����� ��������� ����� ������ (�� �����������, ���� ��� ������� � ��������� ��������� � ��������� � �
Кодировка полетела, проверь чтобы была UTF-8 (без BOM)

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/TelegramBotService.cs
> +        var cancellationToken = cts.Token;
Думаю можно сократить до
var cancellationToken = new CancellationTokenSource().Token;

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/FeedbackMessagesService.cs
> +            return;
Еще похоже тебе сделать не нужен весь message, логично его разделить на text и username

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/FeedbackMessagesService.cs
> +            return;
Если это текстовые поля надежнее их на null проверять через string.IsNullOrEmpty()

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Application/Services/FeedbackService.cs
> +        createdFeedback.FeedbackDate = DateTime.Now.ToUniversalTime();
Почему не DateTime.UtcNow?

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.Persistence/Repositories/EfCoreRepository.cs
> +        if (entity is not null)
Думаю нужно кинуть NotFoundException если пытаемся удалить то, чего нет

2024-08-18 16:38 UTC, joshkhdev commented on PsyAssistFeedback.WebApi/PsyAssistFeedback.WebApi.http
> +GET {{PsyAssistFeedback.WebApi_HostAddress}}/weatherforecast/
Выглядит как лишнее

2024-08-20 21:13 UTC, miitrei commented on PsyAssistFeedback.Application/Services/FeedbackService.cs
> +    private const string EmptyTelegramMessage = "Telegram cannot be empty";
В самой библиотеке бота это называется Username

2024-08-20 21:20 UTC, miitrei commented on PsyAssistFeedback.Application/Services/FeedbackMessagesService.cs
> +            return;
Поднял обработку exceptions наверх, в сервис телеграм-бота, тут  была двойная проверка

2024-08-20 21:23 UTC, miitrei commented on PsyAssistFeedback.Application/Services/TelegramBotService.cs
> +        var cancellationToken = cts.Token;
done

2024-08-20 21:23 UTC, miitrei commented on PsyAssistFeedback.Application/Services/FeedbackService.cs
> +        createdFeedback.FeedbackDate = DateTime.Now.ToUniversalTime();
done

2024-08-20 21:26 UTC, miitrei commented on PsyAssistFeedback.Persistence/Repositories/EfCoreRepository.cs
> +        if (entity is not null)
Мы это делаем в сервисах, это просто репозиторий, здесь не нужна проверка

2024-08-20 21:32 UTC, miitrei commented on PsyAssistFeedback.Persistence/Repositories/EfCoreRepository.cs
> +        if (entity is not null)
Обычно подобные проверки есть в сервисах, возможно это вообще можно убрать. Это из основного проекта

2024-08-20 21:43 UTC, miitrei commented on PsyAssistFeedback.WebApi/PsyAssistFeedback.WebApi.http
> +GET {{PsyAssistFeedback.WebApi_HostAddress}}/weatherforecast/
done

2024-08-20 22:04 UTC, miitrei commented on PsyAssistFeedback.Application/Services/TelegramBotService.cs
> +    private const string HelloMessage = "������ ����! ����� �������� �����, �������, ����������, � ����� ��������� ����� ������ (�� �����������, ���� ��� ������� � ��������� ��������� � ��������� � �
Заменил кодировку файла

2024-08-21 07:35 UTC, joshkhdev approved these changes

2024-09-02 16:15 UTC, merged